name: Catacombs
main: net.steeleyes.catacombs.Catacombs
version: 2.1
depend:
softdepend: [iConomy, BOSEconomy, Currency, MultiCurrency, Permissions, PermissionsEx, PermissionsBukkit]
commands:
    catacombs:
        description: Build catacombs
        aliases: ['cat']