name: Catacombs
main: net.steeleyes.catacombs.Catacombs
version: 1.4
depend:
softdepend: [Permissions,iConomy, BOSEconomy, Currency, MultiCurrency]
commands:
    catacombs:
        description: Build catacombs
        aliases: ['cat']