name: Catacombs
main: net.steeleyes.catacombs.Catacombs
version: 0.8
depend:
softdepend: [Permissions,iConomy, BOSEconomy, Currency, MultiCurrency]
commands:
    catacombs:
        description: Build catacombs
        aliases: ['cat']