name: Catacombs
main: net.steeleyes.catacombs.Catacombs
version: 3.1
depend:
softdepend: [Vault Multiverse]
commands:
    catacombs:
        description: Build catacombs
        aliases: ['cat']