name: Catacombs
main: net.steeleyes.catacombs.Catacombs
version: 2.2
depend:
softdepend: [iConomy, BOSEconomy, Currency, MultiCurrency, Permissions, PermissionsEx, PermissionsBukkit, bPermissions]
commands:
    catacombs:
        description: Build catacombs
        aliases: ['cat']